name: CI (temp)

on:
  push:
    branches: [issue/906]
    paths:
      - "SharePointFramework/**"
      - "Install/**"
      - "Templates/**"
      - .github/workflows/ci-temp.yml

env:
  SP_URL: "https://puzzlepart.sharepoint.com/sites/pp365_900fe5d"
  CI_CREDENTIALS: ${{ secrets.CI_DEV_CREDENTIALS }}

jobs:
  build_release_package:
    name: Build release package
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip-ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Set sha_short
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Setup Node.js 16.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.18.0

      - name: Run Install/Build-Release.ps1 in CI mode
        run: Install/Build-Release.ps1 -CI -SkipBundle
        shell: pwsh

      - uses: actions/upload-artifact@v3
        with:
          name: release-package
          path: release
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}

  upgrade:
    needs: build_release_package
    name: Upgrade
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[skip-upgrade]')"
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release-package
          path: release

      - name: Upgrade
        run: release/Install.ps1 -Url ${{ env.SP_URL }} -Upgrade -CI ${{ env.CI_CREDENTIALS }}
        shell: powershell